package com.example.ite393exam

data class StudentData(
    var lastName: String,
    var firstName: String,
    var middleName: String,
    var studentId: String,
    var password: String,
    var gender: String,
    var birthdate: String,
    var university: String,
    var college: String,
    var course: String,
    var email: String = "None",
    var number: String = "None",
    var fatherNumber: String = "None",
    var motherNumber: String = "None",
    var guardianRelation : String = "None",
    var guardianAddress : String = "None",
    var fatherName: String = "None",
    var motherName: String = "None",
    var guardianName: String = "None",
    var guardianNumber: String = "None",
    var currentAddress: String = "None",
    var permanentAddress: String = "None",
    var currentCountry : String = "None",
    var currentProvince : String = "None",
    var currentCity : String = "None",
    var permanentCountry : String = "None",
    var permanentProvince : String = "None",
    var permanentCity : String = "None"
)
